name: Build iOS IPA
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Install CocoaPods
        run: |
          cd ios
          pod install --repo-update

      - name: Build
        run: |
          cd ios
          xcodebuild -workspace LxMusicMobile.xcworkspace -scheme LxMusicMobile -configuration Release clean build CODE_SIGNING_ALLOWED=NO

      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: LXMusic-iOS
          path: ios/build/Release-iphoneos
