name: Build LxMusic iOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Pod Install
        run: cd ios && pod install

      - name: Build
        run: |
          cd ios
          xcodebuild -workspace LxMusicMobile.xcworkspace \
          -scheme LxMusicMobile \
          -configuration Release \
          -archivePath $PWD/build/LxMusicMobile.xcarchive \
          archive

      - name: Export IPA
        run: |
          cd ios
          xcodebuild -exportArchive \
          -archivePath $PWD/build/LxMusicMobile.xcarchive \
          -exportOptionsPlist <(echo '{"method":"ad-hoc"}') \
          -exportPath $PWD/build

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: LxMusic-iOS
          path: ios/build/*.ipa
